// <auto-generated />
using System;
using Intelligreen.Application;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Intelligreen.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231101035323_Crea plantas")]
    partial class Creaplantas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Intelligreen.Domain.Entity.Planta", b =>
                {
                    b.Property<Guid>("PlantaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("HumedadAmbiente")
                        .HasColumnType("real");

                    b.Property<float>("HumedadTierra")
                        .HasColumnType("real");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreCientifico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("TemperaturaAmbiente")
                        .HasColumnType("real");

                    b.HasKey("PlantaId");

                    b.ToTable("Plantas");
                });
#pragma warning restore 612, 618
        }
    }
}
